# Generated by Django 4.1.2 on 2022-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_management_app', '0002_rename_userprofile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
