# Generated by Django 4.1.2 on 2022-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_management_app', '0005_alter_account_options_alter_account_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('VI', 'Viewer'), ('EM', 'Employee')], max_length=2, null=True),
        ),
    ]
