# Generated by Django 4.1.2 on 2022-11-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_management_app', '0012_alter_account_options_alter_vacationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('Viewer', 'Viewer'), ('Employee', 'Employee')], max_length=8, null=True),
        ),
    ]
